apiVersion: v1
kind: Service
metadata:
  name: flask-demo-service
spec:
  selector:
    app: flask-demo
  ports:
    - port: 80
      targetPort: 8008
      nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
spec:
  selector:
    matchLabels:
      app: flask-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-demo
    spec:
      imagePullSecrets:
        - name: my-registry-key
      containers:
        - name: flask-demo-image
          image: k8s-master:443/flask-demo-container
          command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=8008"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8008
              protocol: TCP
          resources:
            requests:
              cpu: "1"
              memory: "10Mi"
            limits:
              cpu: "4"
              memory: "50Mi"
